# Programación 201

In [2]:
import numpy as np

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [63]:
Array = [[1, 0], [2, -1]]

det = np.linalg.det(Array) ##Determinamente
nor = np.trace(Array) ## Normal de la matriz

print("El determinante de la matriz es: {}".format(det))
print("La norma de la matriz es: {}".format(nor))
# Respuesta

El determinante de la matriz es: -1.0
La norma de la matriz es: 0


### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [18]:
# Respuesta
Array = np.arange(0,1,0.1)
print(Array)
Arcoseno = []
Arcocoseno = []
for i in Array:
    Arcoseno.append(np.arcsin(i))
    Arcocoseno.append(np.arccos(i))   
    
print("El arcoseno de la array es: {}".format(Arcoseno))
print("El arcocoseno de la array es: {}".format(Arcocoseno))



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
El arcoseno de la array es: [0.0, 0.1001674211615598, 0.2013579207903308, 0.3046926540153976, 0.41151684606748806, 0.5235987755982989, 0.6435011087932845, 0.7753974966107532, 0.9272952180016123, 1.1197695149986342]
El arcocoseno de la array es: [1.5707963267948966, 1.4706289056333368, 1.369438406004566, 1.266103672779499, 1.1592794807274085, 1.0471975511965979, 0.9272952180016121, 0.7953988301841435, 0.6435011087932843, 0.45102681179626236]


### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [3]:
# Respuesta
Array = np.random.randint(0,10,100) ##Creo la matriz

print("La media de la serie es: {}".format(np.mean(Array)))
print("La suma de la serie es: {}".format(np.sum(Array)))
print("El valor mínimo de la serie es: {}".format(np.min(Array)))
print("El valor máximo de la serie es: {}".format(np.max(Array)))
print("La desviacion estandar de la serie es: {}".format(np.std(Array)))

La media de la serie es: 4.32
La suma de la serie es: 432
El valor mínimo de la serie es: 0
El valor máximo de la serie es: 9
La desviacion estandar de la serie es: 2.959324247188875


### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [61]:
# Respuesta
Array = np.array([[5,1,7], [0,7,4], [7,23,1]]) ##Se crea la matriz
Array = Array.reshape(3,3)
Array = np.sort(Array) # Se ordena la matriz.
print(Array)


[[ 1  5  7]
 [ 0  4  7]
 [ 1  7 23]]


### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [51]:
# Respuesta

## Creación y dimesionamiento de las matrices

MatrizATamaño = [3,3] 
MatrizA = np.random.randint(0,10,MatrizATamaño[0]*MatrizATamaño[1] )## Creamos la matriz A
MatrizA = MatrizA.reshape(MatrizATamaño[0],MatrizATamaño[1])
print(MatrizA)

MatrizBTamaño = [3,3] 
MatrizB = np.random.randint(0,10,MatrizBTamaño[0]*MatrizBTamaño[1] )## Creamos la matriz B
MatrizB = MatrizB.reshape(MatrizBTamaño[0],MatrizBTamaño[1])
print(MatrizB)



[[2 0 1]
 [8 9 5]
 [7 6 1]]
[[6 0 4]
 [0 2 3]
 [8 0 0]]


In [52]:
def multiplicar_determinantes(A,B): ## Función que realiza la multiplicación
    return np.linalg.det(A)*np.linalg.det(B)

multiplicar_determinantes(MatrizA,MatrizB)


3647.999999999996

### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [41]:
# Respuesta

Identidad1 = z = np.zeros(100,dtype='int') ##Creamos una lista de 10x10 '0'

for i in range(0,100,11): ## Cada 11 filas cambio el valor por 1
    Identidad1[i] = 1
    
    
Identidad1 = Identidad1.reshape(10,10)    
print(Identidad1)

    
## Creacíon de la matriz de identidad usando el generador de matriz identidad
Identidad2 = np.identity(10,dtype=int)
#print(identidad2)
print(Identidad2)

## comparando matrices

print(type(Identidad1))
print(type(Identidad2))

(Identidad1==Identidad2).all()

    

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


True

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [11]:
# Respuesta
i = 2
j = 6

Matriz1 = np.zeros(i*j) ## creo un rango lleno de 0 para empezar a trabajar
Matriz1 = Matriz1.reshape(i,j) ## Doy forma a la matriz

for i1 in range(i): ##Hago un for por todas las filas y columnas en donde aplico la fórmula.
    for j1 in range(j):
        if i % 2 ==0:
            Matriz1[i1][j1] = i1^2+j1
        else:
            Matriz1[i1][j1] = i/(j^2)         

Matriz1


array([[2., 3., 4., 5., 6., 7.],
       [3., 2., 5., 4., 7., 6.]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [27]:
# Respuesta 1: Matrices de 5x5
MatrizA = np.random.randint(0,10,5*5 )## Creamos la matriz A
MatrizA = MatrizA.reshape(5,5)
print(MatrizA)

MatrizB = np.random.randint(0,10,5*5 )## Creamos la matriz B
MatrizB = MatrizB.reshape(5,5)
print(MatrizB)

print(MatrizA*MatrizB) # Multiplica elemento por elemento
print(MatrizA.dot(MatrizB)) # Multiplica las matrices
print(MatrizA@MatrizB) # Otra forma de multiplicar la matriz

[[9 1 1 6 0]
 [5 6 5 7 0]
 [9 0 3 0 5]
 [7 5 0 6 2]
 [1 3 6 5 8]]
[[1 7 3 6 2]
 [8 5 8 4 1]
 [0 4 0 7 0]
 [8 3 9 2 2]
 [2 6 5 3 9]]
[[ 9  7  3 36  0]
 [40 30 40 28  0]
 [ 0  0  0  0  0]
 [56 15  0 12  4]
 [ 2 18 30 15 72]]
[[ 65  90  89  77  31]
 [109 106 126 103  30]
 [ 19 105  52  90  63]
 [ 99 104 125  80  49]
 [ 81 109 112  94  87]]
[[ 65  90  89  77  31]
 [109 106 126 103  30]
 [ 19 105  52  90  63]
 [ 99 104 125  80  49]
 [ 81 109 112  94  87]]


In [36]:
# Respuesta 2: Matrices de 5x5 y 4x5
MatrizA = np.random.randint(0,10,5*5 )## Creamos la matriz A
MatrizA = MatrizA.reshape(5,5)
print(MatrizA)

MatrizB = np.random.randint(0,10,4*5 )## Creamos la matriz B
MatrizB = MatrizB.reshape(5,4)
print(MatrizB)


[[4 6 0 3 0]
 [1 7 1 3 9]
 [0 2 0 0 2]
 [4 3 3 8 8]
 [7 3 8 3 1]]
[[8 3 5 5]
 [1 8 6 9]
 [3 2 0 5]
 [1 3 4 4]
 [7 3 2 3]]


In [35]:
## Falla la multiplicación

print(MatrizA*MatrizB) # Multiplica elemento por elemento
print(MatrizA.dot(MatrizB)) # Multiplica las matrices
print(MatrizA@MatrizB) # Otra forma de multiplicar la matriz

ValueError: operands could not be broadcast together with shapes (5,5) (4,5) 